AWSTemplateFormatVersion: '2010-09-09'
Description: Hello CFn

Parameters:
  VpcName:
    Type: String
    AllowedValues:
      - blue
      - green
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      VpcId:
        Fn::ImportValue: !Sub ${VpcName}-VpcId

